image: docker:git
variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  ROS_DISTRO: foxy

services:
  - docker:dind

before_script:
  - apk update && apk add --no-cache wget git openssh-client bash coreutils tar openssh git py3-pip
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci .industrial_ci
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

clang_format:
    stage: build
    tags:
        - docker-docker
    variables:
        CLANG_FORMAT_VERSION: "10"
        CLANG_FORMAT_CHECK: "file"
    script:
        - .industrial_ci/gitlab.sh
    only:
        - merge_requests
        - master

cmake_format:
  stage: build
  tags:
    - docker-docker
  allow_failure: false
  script:
    - pip3 install cmakelang
    - ./.run-cmake-format && output=$(git diff)
    - if [ -n "$output" ]; then exit 1; else exit 0; fi
  only:
    - merge_requests
    - master

foxy:
  stage: build
  tags:
    - docker-docker
  variables:
    GIT_SUBMODULE_STRATEGY: normal
    DOCKER_IMAGE: mrtd-gitlab.dyn.datasys.swri.edu:5005/swri/ros-i/rosworld2021/roscon2021:latest
    TMPDIR: ${CI_PROJECT_DIR}.tmp
    BUILDER: colcon
    ROS_REPO: main
    PREFIX: snpd_
    UNDERLAY: /root/tesseract-robotics/tesseract_planning_target_ws/install
    UPSTREAM_WORKSPACE: dependencies.rosinstall
    BEFORE_BUILD_UPSTREAM_WORKSPACE_EMBED: 'ici_with_unset_variables source /opt/ros/$ROS_DISTRO/setup.bash'
    ROSDEP_SKIP_KEYS: "tesseract_rviz tesseract_plugins rviz octomap_ros"
    AFTER_SCRIPT: ""
  script:
    - .industrial_ci/gitlab.sh
  only:
    - merge_requests
    - master
