converged: true
initial_cost_per_obs: 1.317809853485645e-05
final_cost_per_obs: 6.177747779108503e-06
target_mount_to_target_pos:
  x: 0.460
  y: 0.0
  z: 0.0
target_mount_to_target_rpy:
  x: 0.0
  y: 0.0
  z: 0.0
camera_mount_to_camera_pos:
  x: -0.15073
  y: -0.1686
  z: 0.07661
camera_mount_to_camera_rpy:
  x: 0.0
  y: -1.571
  z: 0.0
