<?xml version="1.0" ?>
<robot name="motoman_hc10" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="$(find motoman_hc10_support)/urdf/hc10_macro.xacro" />
  <xacro:motoman_hc10 prefix=""/>

  <!-- Add World -->
  <material name="light_gray">
    <color rgba="0.7 0.7 0.7 1"/>
  </material>

  <material name="dark_gray">
    <color rgba="0.3 0.3 0.3 1"/>
  </material>
  
  <link name="world"/>

  <!-- Add Floor -->
  <xacro:property name="length" value="9.0"/>
  <xacro:property name="width" value="6.0"/>
  <link name="floor">
    <visual>
      <origin xyz="0 -${width/10} 0.001" rpy="0 0 0"/>
      <geometry>
        <box size="${length} ${width} 0.001"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 -${width/10} 0.001" rpy="0 0 0"/>
      <geometry>
        <box size="${length} ${width} 0.001"/>
      </geometry>
    </collision>
  </link>
  <joint name="world_to_floor" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <parent link="world"/>
    <child link="floor"/>
  </joint>

  <!-- Add table -->
  <link name="table">
    <visual>
      <geometry>
        <mesh filename="package://snp_support/meshes/collision_demo/Steel Table 4 ft x 6ft.STL"/>
      </geometry>
      <material name="dark_gray"/>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package://snp_support/meshes/collision_demo/convex_hulls/steel_table.ply"/>
      </geometry>
    </collision>
  </link>

  <joint name="floor_to_table" type="fixed">
    <parent link="floor"/>
    <child link="table"/>
  </joint>

  <joint name="table_to_base" type="fixed">
    <parent link="table"/>
    <child link="base_link"/>
    <origin xyz="-0.61 0 0.723" rpy="0 0 0"/> <!-- model doesn't perfectly match .sldprt lenghts -->
  </joint>

  <!-- Add End Effector Components -->
  <link name="pushcorp_base">
    <visual>
      <geometry>
        <mesh filename="package://snp_support/meshes/collision_demo/convex_hulls/afd310.ply"/>
      </geometry>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package://snp_support/meshes/collision_demo/convex_hulls/afd310.ply"/>
      </geometry>
    </collision>
  </link>

  <link name="pushcorp_compliance">
    <visual>
      <geometry>
        <mesh filename="package://snp_support/meshes/collision_demo/rps100.ply"/>
      </geometry>
      <material name="light_gray"/>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package://snp_support/meshes/collision_demo/convex_hulls/rps100.ply"/>
      </geometry>
    </collision>
  </link>

  <link name="pushcorp_backplate">
    <visual>
      <geometry>
        <mesh filename="package://snp_support/meshes/collision_demo/backplate.ply"/>
      </geometry>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package://snp_support/meshes/collision_demo/convex_hulls/backplate.ply"/>
      </geometry>
    </collision>
  </link>

  <joint name="tool0_to_pushcorp_backplate" type="fixed">
    <parent link="tool0"/>
    <child link="pushcorp_backplate"/>
    <origin xyz="0 0 0" rpy="0 0 ${radians(180)}"/>
  </joint>

  <link name="pushcorp_camera1">
    <visual>
      <geometry>
        <mesh filename="package://snp_support/meshes/collision_demo/camera1.ply"/>
      </geometry>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package://snp_support/meshes/collision_demo/convex_hulls/camera1.ply"/>
      </geometry>
    </collision>
  </link>

  <joint name="tool0_to_pushcorp_camera1" type="fixed">
    <parent link="tool0"/>
    <child link="pushcorp_camera1"/>
    <origin xyz="0 0 0" rpy="0 0 ${radians(180)}"/>
  </joint>

  <link name="pushcorp_camera2">
    <visual>
      <geometry>
        <mesh filename="package://snp_support/meshes/collision_demo/camera2.ply"/>
      </geometry>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package://snp_support/meshes/collision_demo/convex_hulls/camera2.ply"/>
      </geometry>
    </collision>
  </link>

  <joint name="tool0_to_pushcorp_camera2" type="fixed">
    <parent link="tool0"/>
    <child link="pushcorp_camera2"/>
    <origin xyz="0 0 0" rpy="0 0 ${radians(180)}"/>
  </joint>

  <link name="pushcorp_frontplate">
    <visual>
      <geometry>
        <mesh filename="package://snp_support/meshes/collision_demo/frontplate.ply"/>
      </geometry>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package://snp_support/meshes/collision_demo/convex_hulls/front.ply"/>
      </geometry>
    </collision>
  </link>

  <joint name="tool0_to_pushcorp_frontplate" type="fixed">
    <parent link="tool0"/>
    <child link="pushcorp_frontplate"/>
    <origin xyz="0 0 0" rpy="0 0 ${radians(180)}"/>
  </joint>

  <joint name="tool0_to_pushcorp_base" type="fixed">
    <parent link="tool0"/>
    <child link="pushcorp_base"/>
    <origin xyz="0 0 0" rpy="0 0 ${radians(180)}"/>
  </joint>

  <link name="pushcorp_sidebracket1">
    <visual>
      <geometry>
        <mesh filename="package://snp_support/meshes/collision_demo/sidebracket1.ply"/>
      </geometry>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package://snp_support/meshes/collision_demo/convex_hulls/bracket1.ply"/>
      </geometry>
    </collision>
  </link>

  <joint name="tool0_to_pushcorp_sidebracket1" type="fixed">
    <parent link="tool0"/>
    <child link="pushcorp_sidebracket1"/>
    <origin xyz="0 0 0" rpy="0 0 ${radians(180)}"/>
  </joint>

  <link name="pushcorp_sidebracket2">
    <visual>
      <geometry>
        <mesh filename="package://snp_support/meshes/collision_demo/sidebracket2.ply"/>
      </geometry>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package://snp_support/meshes/collision_demo/convex_hulls/bracket2.ply"/>
      </geometry>
    </collision>
  </link>

  <joint name="tool0_to_pushcorp_sidebracket2" type="fixed">
    <parent link="tool0"/>
    <child link="pushcorp_sidebracket2"/>
    <origin xyz="0 0 0" rpy="0 0 ${radians(180)}"/>
  </joint>

  <joint name="tool0_to_pushcorp_actuator" type="fixed">
    <parent link="tool0"/>
    <child link="pushcorp_compliance"/>
    <origin xyz="0 0 0" rpy="0 0 ${radians(180)}"/>
  </joint>

  <link name="camera_link"/>

  <!-- Add Target Calibration -->
  <link name="target_base_link">
    <visual>
      <geometry>
        <mesh filename="package://snp_support/meshes/rosWorldCalib.dae"/>
      </geometry>
    </visual>
  </link>

  <joint name="robot_to_camera_joint" type="fixed">
    <parent link="tool0"/>
    <child link="camera_link"/>
    <origin xyz="0.175 0 0" rpy="0 0 0"/>
  </joint>

  <joint name="world_to_target_joint" type="fixed">
    <parent link="floor"/>
    <child link="target_base_link"/>
    <origin xyz="0.37565 0.2809875 0.723" rpy="${pi/2} 0 ${pi}"/>
  </joint>

  <link name="camera_color_optical_frame"/>
  <link name="target_cal_frame"/>

  <joint name="camera_cal_joint" type="fixed">
    <parent link="camera_link"/>
    <child link="camera_color_optical_frame"/>
  </joint>

  <joint name="target_cal_joint" type="fixed">
    <parent link="floor"/>
    <child link="target_cal_frame"/>
    <origin xyz="0.37565 0.2809875 0.723" rpy="${pi/2} 0 ${pi}"/>
  </joint>

  <!-- Add TCP -->
  <link name="sand_tcp"/>
  <joint name="sand_tcp_joint" type="fixed">
    <parent link="tool0"/>
    <child link="sand_tcp"/>
    <origin xyz="0.23261 0 0.08259" rpy="${radians(90)} 0 ${radians(90)}"/> <!-- values from solidworks -->
  </joint>

</robot>
