<?xml version="1.0" ?>
<robot name="motoman_hc10" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="$(find motoman_hc10_support)/urdf/hc10_macro.xacro" />
  <xacro:motoman_hc10 prefix=""/>

  <!-- Add World -->
  <material name="light_gray">
    <color rgba="0.7 0.7 0.7 1"/>
  </material>

  <material name="dark_gray">
    <color rgba="0.3 0.3 0.3 1"/>
  </material>
  
  <link name="world"/>

  <!-- Add Floor -->
  <xacro:property name="length" value="9.0"/>
  <xacro:property name="width" value="6.0"/>
  <link name="floor">
    <visual>
      <origin xyz="0 -${width/10} 0.001" rpy="0 0 0"/>
      <geometry>
        <box size="${length} ${width} 0.001"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 -${width/10} 0.001" rpy="0 0 0"/>
      <geometry>
        <box size="${length} ${width} 0.001"/>
      </geometry>
    </collision>
  </link>
  <joint name="world_to_floor" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <parent link="world"/>
    <child link="floor"/>
  </joint>

  <!-- Add table -->
  <link name="table">
    <visual>
      <geometry>
        <mesh filename="package://snp_support/meshes/visual/steel_table.ply"/>
      </geometry>
      <material name="dark_gray"/>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package://snp_support/meshes/collision/steel_table.ply"/>
      </geometry>
    </collision>
  </link>

  <joint name="floor_to_table" type="fixed">
    <parent link="floor"/>
    <child link="table"/>
  </joint>

  <joint name="table_to_base" type="fixed">
    <parent link="table"/>
    <child link="base_link"/>
    <origin xyz="-0.61 0 0.723" rpy="0 0 0"/>end_effector.ply
  </joint>

  <!-- Add End Effector Components -->
  <link name="ee">
    <visual>
      <geometry>
        <mesh filename="package://snp_support/meshes/visual/end_effector.stl"/>
      </geometry>
    </visual>
    <collision name="compliance">
      <geometry>
        <mesh filename="package://snp_support/meshes/collision/afd310.ply"/>
      </geometry>
    </collision>
    <collision name="spindle">
      <geometry>
        <mesh filename="package://snp_support/meshes/collision/rps100.ply"/>
      </geometry>
    </collision>
    <collision name="backplate">
      <geometry>
        <mesh filename="package://snp_support/meshes/collision/backplate.ply"/>
      </geometry>
    </collision>
    <collision name="frontplate">
      <geometry>
        <mesh filename="package://snp_support/meshes/collision/front.ply"/>
      </geometry>
    </collision>
    <collision name="camera1">
      <geometry>
        <mesh filename="package://snp_support/meshes/collision/camera1.ply"/>
      </geometry>
    </collision>
    <collision name="camera2">
      <geometry>
        <mesh filename="package://snp_support/meshes/collision/camera2.ply"/>
      </geometry>
    </collision>
    <collision name="sidebracket1">
      <geometry>
        <mesh filename="package://snp_support/meshes/collision/bracket1.ply"/>
      </geometry>
    </collision>
    <collision name="sidebracket2">
      <geometry>
        <mesh filename="package://snp_support/meshes/collision/bracket2.ply"/>
      </geometry>
    </collision>
  </link>

  <joint name="tool0_to_ee" type="fixed">
    <parent link="tool0"/>
    <child link="ee"/>
  </joint>

  <!-- Calibration -->
  <link name="camera_color_optical_frame"/>
  <joint name="camera_cal_joint" type="fixed">
    <parent link="tool0"/>
    <child link="camera_color_optical_frame"/>
    <origin xyz="-0.150 0.140 0.08259" rpy="0 ${radians(-90)} 0"/>
  </joint>

  <link name="target_cal_frame">
    <visual>
      <geometry>
        <mesh filename="package://snp_support/meshes/rosWorldCalib.dae"/>
      </geometry>
    </visual>
  </link>
  <joint name="target_cal_joint" type="fixed">
    <parent link="floor"/>
    <child link="target_cal_frame"/>
    <origin xyz="0.37565 0.2809875 0.723" rpy="${radians(90)} 0 ${radians(180)}"/>
  </joint>

  <!-- Add TCP -->
  <link name="sand_tcp"/>
  <joint name="sand_tcp_joint" type="fixed">
    <parent link="tool0"/>
    <child link="sand_tcp"/>
    <origin xyz="-0.23261 0 0.08259" rpy="${radians(-90)} 0 ${radians(90)}"/>
  </joint>

</robot>
