kinematic_plugins:
  inv_kin_plugins:
    manipulator:
      OPWInvKin:
        class: OPWInvKinFactory
        default: true
        config:
          base_link: base_link
          tip_link: tool0
          params:
            a1: 0.175
            a2: -0.175
            b: 0.00
            c1: 0.495
            c2: 0.9
            c3: 0.96
            c4: 0.135
            offsets: [0, 0, -1.57079632679, 0, 0, 0]
            sign_corrections: [1, 1, 1, 1, 1, 1]
